In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib 
matplotlib.style.use('ggplot') # make the plots a little bit prettier

%matplotlib inline

In [3]:
df_train = pd.read_csv('../data/sales_train.csv')

In [21]:
print(df_train.head())
df_train.shop_id = pd.Categorical(df_train.shop_id)
df_train.item_id = pd.Categorical(df_train.item_id)

         date  date_block_num shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0      59    22154      999.00           1.0
1  03.01.2013               0      25     2552      899.00           1.0
2  05.01.2013               0      25     2552      899.00          -1.0
3  06.01.2013               0      25     2554     1709.05           1.0
4  15.01.2013               0      25     2555     1099.00           1.0

In [22]:
print(df_train.date.describe())
print(df_train.item_id.describe())
print(df_train.shop_id.describe())

count        2935849
unique          1034
top       28.12.2013
freq            9434
Name: date, dtype: object
count     2935849
unique      21807
top         20949
freq        31340
Name: item_id, dtype: int64
count     2935849
unique         60
top            31
freq       235636
Name: shop_id, dtype: int64

In [26]:
df_train[['shop_id','item_price']].groupby('shop_id').agg('sum')

           item_price
shop_id
0        5.553869e+06
1        2.926161e+06
2        3.510444e+07
3        2.647262e+07
4        3.533539e+07
5        3.326088e+07
6        7.455831e+07
7        5.607710e+07
8        2.226273e+06
9        4.714303e+06
10       1.644284e+07
11       4.798425e+05
12       5.080559e+07
13       5.333601e+06
14       3.600645e+07
15       5.559759e+07
16       4.871298e+07
17       2.352167e+07
18       6.251643e+07
19       5.430200e+07
20       2.389266e+06
21       5.147937e+07
22       4.224514e+07
23       5.023142e+06
24       5.628828e+07
25       1.555576e+08
26       4.851612e+07
27       1.056489e+08
28       1.252947e+08
29       4.528771e+07
30       3.885892e+07
31       1.707634e+08
32       5.098652e+06
33       5.594080e+06
34       7.695497e+06
35       5.682312e+07
36       3.568190e+05
37       3.734868e+07
38       5.360325e+07
39       1.501239e+07
40       4.080156e+06
41       3.828370e+07
42       1.015515e+08
43       4.275150e+07
44       2.941958e+07
45       3.377880e+07
46       6.093469e+07
47       6.280522e+07
48       2.429822e+07
49       1.833824e+07
50       6.335695e+07
51       2.185559e+07
52       3.764912e+07
53       4.792886e+07
54       1.096694e+08
55       2.113586e+07
56       5.169638e+07
57       9.131521e+07
58       5.846344e+07
59       3.726479e+07